"""Autonomous Medical Index RAG Compiler Orchestrator.

Compiles back-of-the-book index markdown and finished chapter RAG files
(*_RAG_Optimised.md) into the complete 26-Asset Index Intelligence Suite.
"""

from __future__ import annotations

import argparse
import glob
import io
import json
import os
import re
import sys
import time
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set, Tuple



TRUST_CLASSIFIER = None  # tests may replace; resolved lazily from the RAG pipeline skill


def get_trust_classifier():
    """Loads build_chapter_trust_record from davidson-rag-pipeline-antigravity without leaving it on sys.path."""
    global TRUST_CLASSIFIER
    if TRUST_CLASSIFIER is not None:
        return TRUST_CLASSIFIER
    skills_root = os.environ.get("CDSS_SKILLS_ROOT", os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    rag_dir = os.path.join(skills_root, "davidson-rag-pipeline-antigravity")
    added = rag_dir not in sys.path
    try:
        if added:
            sys.path.insert(0, rag_dir)
        from pipeline.stages.trust_ledger import build_chapter_trust_record
        TRUST_CLASSIFIER = build_chapter_trust_record
    except Exception as e:
        print(f"[WARN] Cannot load pipeline trust classifier from {rag_dir}: {e}", file=sys.stderr)
        return None
    finally:
        if added and rag_dir in sys.path:
            sys.path.remove(rag_dir)
    return TRUST_CLASSIFIER


# Tokens keep acronyms and alphanumerics (AF, MI, T2DM, HbA1c, SGLT2, CD4). The old pattern
# `\b[a-zA-Z]{3,25}\b` dropped every 2-letter term and every term containing a digit.
_TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9\-]{1,24}")
_GENERIC_TITLE_WORDS = frozenset({"disease", "diseases", "management", "clinical", "treatment", "syndrome", "syndromes",
                                  "disorder", "disorders", "general", "overview", "introduction", "features", "other",
                                  "common", "acute", "chronic", "therapy", "diagnosis"})


def tokenize(text: str) -> List[str]:
    return [m.group(0).lower() for m in _TOKEN_RE.finditer(text or "")]


# A small but REAL retrieval router (lexical IDF over the compiled catalog). Replaces the former stub that
# only printed "Query received". It implements --query/--vignette and says plainly that the other modes
# (--validate-therapy/--outline/--diff) are not implemented, instead of pretending.
ROUTER_TEMPLATE = r'''"""Lexical CDSS router for __TITLE__ (generated by medical-index-rag-compiler).
Implements: --query, --vignette (IDF-weighted term overlap over the compiled catalog).
NOT implemented (exit 2): --validate-therapy, --outline, --diff."""
import argparse, glob, json, math, os, re, sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
TOK = re.compile(r"[A-Za-z][A-Za-z0-9\-]{1,24}")


def _load(pattern):
    hits = sorted(glob.glob(os.path.join(HERE, pattern)))
    if not hits:
        sys.exit(f"[ROUTER ERROR] {pattern} not found next to the router ({HERE}); re-run the compiler.")
    with open(hits[0], encoding="utf-8") as f:
        return json.load(f)


def search(query, top_k=5):
    catalog, inv = _load("*_chunks_master_catalog.json"), _load("*_inverted_chunk_index.json")
    n = max(len(catalog), 1)
    scores = {}
    for tok in set(m.group(0).lower() for m in TOK.finditer(query)):
        docs = inv.get(tok, [])
        if not docs:
            continue
        idf = math.log(1 + n / len(docs))
        for d in docs:
            scores[d] = scores.get(d, 0.0) + idf
    ranked = sorted(scores.items(), key=lambda kv: (-kv[1], kv[0]))[:top_k]
    return [{"chunk_id": catalog[d]["chunk_id"], "section": catalog[d]["section"], "topic": catalog[d]["topic"],
             "score": round(s, 4), "excerpt": catalog[d]["body"][:300]} for d, s in ranked]


class CDSSRouter:
    """Class interface expected by cdss-retrieval-packager (`retrieve_chunks`)."""

    def retrieve_chunks(self, query, top_k=5, compress=False):
        res = search(query, max(int(top_k), 1))
        if compress:
            for r in res:
                r["excerpt"] = r["excerpt"][:160]
        return res


HarrisonCDSSRouter = CDSSRouter


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--query"); ap.add_argument("--vignette"); ap.add_argument("--top_k", type=int, default=5)
    ap.add_argument("--compress", action="store_true"); ap.add_argument("--json", action="store_true")
    ap.add_argument("--validate-therapy", nargs="*"); ap.add_argument("--outline"); ap.add_argument("--diff")
    a = ap.parse_args()
    if a.validate_therapy is not None or a.outline or a.diff:
        print("[ROUTER] --validate-therapy / --outline / --diff are not implemented by the generated router.", file=sys.stderr)
        sys.exit(2)
    q = a.query or a.vignette
    if not q:
        ap.print_help(); sys.exit(0)
    res = search(q, max(a.top_k, 1))
    if a.json:
        print(json.dumps({"query": q, "results": res}, ensure_ascii=False))
    else:
        for r in res:
            print(f"[{r['score']}] {r['chunk_id']} | {r['section']} | {r['topic']}")
            print("   " + (r["excerpt"][:160] if a.compress else r["excerpt"]))
        if not res:
            print("No matching chunks.")


if __name__ == "__main__":
    sys.exit(main())
'''


@dataclass
class CompilerConfig:
    book_title: str
    edition: str
    corpus_root: str
    index_markdown_path: str
    output_dir: str
    asset_prefix: str = ""
    eval_triplets_count: int = 768
    skip_eval: bool = False
    dry_run: bool = False
    allow_unverified: bool = False

    def __post_init__(self):
        if not self.asset_prefix:
            # Auto-derive short clean prefix from book title
            words = re.findall(r"\b[A-Za-z0-9]+\b", self.book_title)
            self.asset_prefix = words[0].lower() if words else "book"


class MedicalBookIndexCompiler:
    """Orchestrator executing the 6-phase compilation flow."""

    def __init__(self, config: CompilerConfig):
        self.config = config
        if not self.config.dry_run:
            os.makedirs(self.config.output_dir, exist_ok=True)
        self.inverted_index: Dict[str, List[int]] = {}
        self.chunks_catalog: List[Dict[str, Any]] = []
        self.index_terms: List[Dict[str, Any]] = []
        self.index_lines: List[str] = []
        self.manifest: Dict[str, Any] = {}

    def log(self, stage: str, message: str):
        t_stamp = time.strftime("%H:%M:%S")
        print(f"[{t_stamp}] [{stage}] {message}")

    def run_all(self) -> Dict[str, Any]:
        """Runs all 6 deterministic compilation phases."""
        t_start = time.time()
        self.log("START", f"Compiling Index Intelligence for: {self.config.book_title} ({self.config.edition})")

        # Phase 1: Ingest & Parse Index
        self.phase_1_ingest_index()

        # Phase 2: Ingest Chunks & Build Inverted Index
        self.phase_2_catalog_chunks_and_inverted_index()

        # Phase 3: Synthesize Knowledge Graphs & Guardrails
        self.phase_3_synthesize_knowledge_graphs()

        # Phase 4: Build Next-Gen Optimizers & Constrained Decoding
        self.phase_4_build_nextgen_optimizers()

        # Phase 5: Run Automated Benchmark Evaluation
        if not self.config.skip_eval:
            self.phase_5_benchmark_retrieval()
        else:
            self.log("PHASE 5", "Skipping benchmark evaluation (--skip-eval specified)")

        # Phase 6: Scaffold Turnkey Router & Skill
        self.phase_6_scaffold_router_and_skill()

        total_elapsed = round(time.time() - t_start, 2)
        self.log("FINISH", f"All compilation phases completed successfully in {total_elapsed}s!")

        # Save manifest
        self.manifest = {
            "book_title": self.config.book_title,
            "edition": self.config.edition,
            "asset_prefix": self.config.asset_prefix,
            "total_index_terms": len(self.index_terms),
            "total_chunks": len(self.chunks_catalog),
            "compiled_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "output_directory": self.config.output_dir,
            "runtime_seconds": total_elapsed,
        }
        self.manifest["benchmark_verdict"] = getattr(self, "benchmark_verdict", "SKIPPED")
        self._write_json("INDEX_INTELLIGENCE_MANIFEST.json", self.manifest, indent=2)

        return self.manifest

    def phase_1_ingest_index(self):
        """Phase 1: Parse Index Markdown into taxonomies, acronyms, and anchors."""
        self.log("PHASE 1", f"Parsing Index Markdown from: {self.config.index_markdown_path}")
        if not os.path.exists(self.config.index_markdown_path):
            raise FileNotFoundError(f"Index markdown file not found: {self.config.index_markdown_path}")

        with open(self.config.index_markdown_path, encoding="utf-8") as f:
            raw_lines = [line.strip() for line in f if line.strip()]

        self.index_lines = raw_lines
        hierarchy: Dict[str, List[str]] = {}
        synonyms: Dict[str, Any] = {}
        trials: List[Dict[str, Any]] = []
        anchors: List[Dict[str, Any]] = []

        current_parent: Optional[str] = None
        current_subfacets: List[str] = []

        # Regex extractors
        trial_pattern = re.compile(r"\b([A-Z0-9\-]{2,15})\s*\(([^)]+)\)\s*(?:trial|study|investigation|registry)", re.IGNORECASE)
        acronym_pattern = re.compile(r"([A-Za-z0-9\s\-]+)\s*\(([A-Z0-9\-]{2,10})\)")
        page_pattern = re.compile(r"(\d+)(?:–|-)(\d+)|(\d+)([tfc]?)")

        for line in raw_lines:
            if line.startswith("#") or line.startswith("Note:"):
                continue

            # Check if sub-facet or primary concept
            is_sub = (line and line[0].islower() and not line.startswith("$")) or any(
                line.startswith(p) for p in ["in ", "of ", "for ", "with ", "as ", "and ", "vs."]
            )

            if is_sub and current_parent:
                current_subfacets.append(line)
            else:
                if current_parent:
                    self.index_terms.append({"term": current_parent, "sub_entries": list(current_subfacets)})
                    hierarchy[current_parent] = list(current_subfacets)
                current_parent = line
                current_subfacets = []

            # Check for clinical trials
            tm = trial_pattern.search(line)
            if tm:
                trials.append({
                    "entry": line,
                    "acronym": tm.group(1),
                    "title": tm.group(2)
                })

            # Check for acronyms
            am = acronym_pattern.search(line)
            if am:
                canon = am.group(1).strip()
                acro = am.group(2).strip()
                if len(acro) >= 2 and acro.isupper():
                    entry = synonyms.setdefault(acro, {"canonical_terms": [], "type": "acronym_expansion"})
                    if canon not in entry["canonical_terms"]:
                        entry["canonical_terms"].append(canon)   # PE -> Pulmonary embolism AND Pre-eclampsia

            # Check for typographical anchors (t, f, c, ranges)
            for pm in page_pattern.finditer(line):
                if pm.group(1) and pm.group(2):
                    anchors.append({
                        "concept": current_parent or line,
                        "page_start": pm.group(1),
                        "page_end": pm.group(2),
                        "anchor_type": "page_interval"
                    })
                elif pm.group(3) and pm.group(4):
                    t_type = "table_anchor" if pm.group(4) == "t" else ("figure_anchor" if pm.group(4) == "f" else "plate_anchor")
                    anchors.append({
                        "concept": current_parent or line,
                        "page": pm.group(3),
                        "anchor_type": t_type,
                        "raw_token": f"{pm.group(3)}{pm.group(4)}"
                    })

        if current_parent:
            self.index_terms.append({"term": current_parent, "sub_entries": list(current_subfacets)})
            hierarchy[current_parent] = list(current_subfacets)

        p = self.config.asset_prefix
        # Write Phase 1 outputs
        self._write_json("cardiology_synonyms_and_acronyms.json", synonyms)
        self._write_json("landmark_clinical_trials_registry.json", trials)
        self._write_json("index_concept_hierarchy.json", hierarchy)
        self._write_json(f"{p}_typographical_anchors.json", anchors)

        self.log("PHASE 1", f"Extracted {len(self.index_terms)} index concepts, {len(synonyms)} acronyms, {len(trials)} trials, {len(anchors)} anchors.")

    def phase_2_catalog_chunks_and_inverted_index(self):
        """Phase 2: Ingest RAG chunks, build master catalog and inverted index."""
        self.log("PHASE 2", f"Scanning for *_RAG_Optimised.md files in: {self.config.corpus_root}")
        chunk_files = glob.glob(os.path.join(self.config.corpus_root, "**", "*_RAG_Optimised.md"), recursive=True)
        if not chunk_files:
            # Fallback: scan current directory
            chunk_files = glob.glob(os.path.join(self.config.corpus_root, "*_RAG_Optimised.md"))

        self.log("PHASE 2", f"Discovered {len(chunk_files)} production chapter RAG files.")
        chunks: List[Dict[str, Any]] = []
        inverted_index: Dict[str, List[int]] = defaultdict(list)
        def chapter_trust(cf_path: str) -> str:
            """Returns "" if the chapter output is trusted for indexing, else the reason it is excluded.

            Uses the RAG pipeline's own classify_trust() (the logic behind CORPUS_TRUST_STATUS.md) on the
            folder holding the *_RAG_Optimised.md. Protection markers and the Stage 8 checkpoint flag alone
            are not trust evidence.
            """
            classifier = get_trust_classifier()
            if classifier is None:
                return "pipeline trust classifier unavailable"
            out_dir = os.path.dirname(cf_path)
            try:
                rec = classifier(out_dir, os.path.basename(os.path.dirname(out_dir)))
            except Exception as e:
                return f"trust classification failed: {e}"
            if not rec:
                return "no pipeline evidence (checkpoint) in output folder"
            if rec.get("trusted_for_downstream_use") is not True:
                return f"not trusted ({rec.get('classification')})"
            return ""

        # One copy per chapter file: prefer the canonical "rag_pipeline_output" folder, shallowest path;
        # skip backup / audit / verification-bundle copies entirely.
        root = os.path.abspath(self.config.corpus_root)
        def _rel(p):
            return os.path.relpath(os.path.abspath(p), root).lower()
        chunk_files = [p for p in chunk_files if not any(k in _rel(p) for k in ("backup", "audit", "bundle"))]
        by_name = {}
        for p in sorted(chunk_files, key=lambda p: (os.path.basename(os.path.dirname(p)) != "rag_pipeline_output",
                                                    _rel(p).count(os.sep), p)):
            by_name.setdefault(os.path.basename(p), []).append(p)
        chunk_files = []
        for name, paths in by_name.items():
            chunk_files.append(paths[0])
            for dup in paths[1:]:
                self.log("PHASE 2", f"Skipping duplicate copy of {name}: {os.path.relpath(dup, root)}")

        excluded = []
        chunk_counter = 0
        for cf in sorted(chunk_files):
            reason = chapter_trust(cf)
            if reason:
                if self.config.allow_unverified:
                    self.log("PHASE 2", f"WARNING: including UNVERIFIED chapter ({reason}): {os.path.basename(cf)}")
                else:
                    excluded.append((os.path.basename(cf), reason))
                    self.log("PHASE 2", f"Excluding untrusted chapter ({reason}): {os.path.basename(cf)}")
                    continue

            sec_name = os.path.basename(os.path.dirname(cf))
            if sec_name.lower() in ["rag_pipeline_output", "output"]:
                sec_name = os.path.basename(os.path.dirname(os.path.dirname(cf)))

            with open(cf, encoding="utf-8") as f:
                content = f.read()

            # Split on every line-anchored "---\nchunk_id:" opener, including one at the very start of the file
            # (the old split needed a preceding newline and then discarded raw_chunks[0], dropping the first chunk).
            starts = [m for m in re.finditer(r"(?m)^---[ \t]*\r?\nchunk_id:[ \t]*", content)]
            raw_chunks = [content[m.end(): (starts[i + 1].start() if i + 1 < len(starts) else len(content))]
                          for i, m in enumerate(starts)]
            for idx, raw in enumerate(raw_chunks, start=1):
                c_id_match = re.match(r"([A-Za-z0-9_\-]+)", raw)
                c_id = c_id_match.group(1) if c_id_match else f"{sec_name}_CHUNK_{idx}"

                # Topic match
                topic_match = re.search(r"(?m)^(?:topic_primary|topic):[ \t]*(.+?)[ \t]*$", raw)
                topic = topic_match.group(1).strip() if topic_match else "General Medical Topic"
                if len(topic) >= 2 and topic[0] == topic[-1] and topic[0] in "\"'":
                    topic = topic[1:-1]            # strip ONE pair of wrapping quotes; apostrophes inside stay

                # Type match
                type_match = re.search(r"semantic_type:\s*[\"']?([^\"'\n]+)[\"']?", raw)
                c_type = type_match.group(1) if type_match else "concept_overview"

                # Body extraction
                body_parts = raw.split("---", 1)
                body = body_parts[1].strip() if len(body_parts) > 1 else raw.strip()
                # a "### Chunk N" divider precedes the NEXT chunk's "---" opener; it is not this chunk's content
                body = re.sub(r"(?:\r?\n)+#{1,6}[ \t]+Chunk\b[^\n]*\s*$", "", body)

                chunk_entry = {
                    "chunk_id": c_id,
                    "local_id": f"L2-{idx:03d}",
                    "section": sec_name,
                    "topic": topic,
                    "type": c_type,
                    "word_count": len(body.split()),
                    "body": body[:8000]  # Store first 8k chars
                }
                chunks.append(chunk_entry)

                # Tokenize for inverted index
                tokens = set(tokenize(topic + " " + body))
                for tok in tokens:
                    inverted_index[tok].append(chunk_counter)

                chunk_counter += 1

        self.chunks_catalog = chunks
        self.inverted_index = dict(inverted_index)
        truncated = sum(1 for c in chunks if c.get("word_count", 0) and len(c.get("body", "")) >= 8000)
        if truncated:
            self.log("PHASE 2", f"WARNING: {truncated} chunk body(ies) exceeded 8000 chars and were truncated in the catalog")
        if excluded:
            self.log("PHASE 2", f"Excluded {len(excluded)} untrusted chapter(s); re-run with --allow-unverified to include them")
        p = self.config.asset_prefix
        self._write_json(f"{p}_chunks_master_catalog.json", chunks)
        self._write_json(f"{p}_inverted_chunk_index.json", dict(inverted_index))

        # Build trial and synonym chunk mappings
        trials_reg = self._read_json("landmark_clinical_trials_registry.json", default=[])
        trials_map: Dict[str, Any] = {}
        for tr in trials_reg:
            acro = tr.get("acronym")
            if not acro:
                continue
            matched_chunks = []
            pat = re.compile(rf"\b{re.escape(acro)}\b", re.IGNORECASE)
            for c in chunks:
                if pat.search(c["topic"]) or pat.search(c["body"]):
                    matched_chunks.append({"chunk_id": c["chunk_id"], "section": c["section"], "topic": c["topic"]})
            if matched_chunks:
                trials_map[acro] = {
                    "entry": tr.get("entry", acro),
                    "acronym": acro,
                    "matches_count": len(matched_chunks),
                    "chunks": matched_chunks[:15]
                }
        self._write_json(f"{p}_trial_to_chunks_map.json", trials_map)

        syn_reg = self._read_json("cardiology_synonyms_and_acronyms.json", default={})
        syn_map: Dict[str, Any] = {}
        for acro, sdata in syn_reg.items():
            matched_chunks = []
            pat = re.compile(rf"\b{re.escape(acro)}\b")
            for c in chunks:
                if pat.search(c["topic"]) or pat.search(c["body"][:1000]):
                    matched_chunks.append({"chunk_id": c["chunk_id"], "topic": c["topic"]})
            if matched_chunks:
                syn_map[acro] = {
                    "canonical_terms": sdata.get("canonical_terms", []),
                    "type": sdata.get("type", "synonym"),
                    "matches_count": len(matched_chunks),
                    "chunks": matched_chunks[:10]
                }
        self._write_json(f"{p}_synonym_to_chunks_map.json", syn_map)

        self.log("PHASE 2", f"Cataloged {len(chunks)} chunks across {len(inverted_index)} indexed vocabulary terms.")

    def phase_3_synthesize_knowledge_graphs(self):
        """Phase 3: Synthesize subtrees, directed cross-references, safety matrix, and early-exit index."""
        p = self.config.asset_prefix
        self.log("PHASE 3", "Synthesizing concept subtrees, directed graphs, and safety matrices...")

        subtrees: Dict[str, Any] = {}
        directed_graph: Dict[str, List[Dict[str, str]]] = defaultdict(list)
        polysemy_candidates: Dict[str, List[str]] = defaultdict(list)

        for item in self.index_terms:
            term = item["term"]
            subs = item["sub_entries"]
            if len(subs) >= 3:
                subtrees[term.lower()] = {
                    "parent_concept": term,
                    "subfacets_count": len(subs),
                    "subfacets": subs
                }

            # Check cross-references: See / See also
            see_match = re.search(r"\bSee (?:also )?([A-Za-z0-9\s,\-]+)", term)
            if see_match:
                tgt = see_match.group(1).strip()
                directed_graph[term].append({"target": tgt, "relationship": "cross_reference"})

            # Check polysemy
            first_word = term.split()[0].lower() if term else ""
            if first_word and len(first_word) >= 4:
                polysemy_candidates[first_word].append(term)

        # Polysemy hubs
        polysemy_hubs: Dict[str, Any] = {}
        for kw, branches in polysemy_candidates.items():
            if len(branches) >= 4:
                polysemy_hubs[kw] = {
                    "keyword": kw,
                    "branches_count": len(branches),
                    "clinical_branches": [{"entry": b} for b in branches[:10]]
                }

        # Drug-Disease Safety Matrix: DERIVED from the chunks. Each entry lists where the drug is mentioned
        # (chunk ids, section, semantic type). No indication/precaution prose is invented: the former version
        # gave nine drugs (incl. metformin) the same "Cardiovascular pharmacotherapy / Monitor renal function" text.
        drugs = ["sacubitril", "spironolactone", "aspirin", "metformin", "amiodarone", "digoxin", "apixaban", "warfarin", "furosemide"]
        matrix: Dict[str, Any] = {}
        for d in drugs:
            pat = re.compile(rf"(?<![A-Za-z0-9]){re.escape(d)}(?![A-Za-z0-9])", re.I)
            hits = [c for c in self.chunks_catalog if pat.search(c["topic"]) or pat.search(c["body"])]
            matrix[d] = {
                "matches_count": len(hits),
                "chunk_ids": [c["chunk_id"] for c in hits[:25]],
                "sections": sorted({c["section"] for c in hits})[:10],
                "semantic_types": sorted({c["type"] for c in hits}),
                "note": "locations only; read the cited chunks for indications and precautions" if hits
                        else "no mention found in the indexed (trusted) chunks",
            }
        safety_matrix: Dict[str, Any] = {
            "metadata": {"derived_from": "indexed chunks", "total_indexed_drugs": sum(1 for v in matrix.values() if v["matches_count"]),
                         "drugs_checked": len(drugs)},
            "matrix": matrix,
        }

        # Early Exit Section Index
        early_exit: Dict[str, Any] = {}
        for c in self.chunks_catalog:
            t_words = re.findall(r"\b[a-z]{4,15}\b", c["topic"].lower())
            for w in [w for w in t_words if w not in _GENERIC_TITLE_WORDS][:3]:
                if w not in early_exit:
                    early_exit[w] = {
                        "target_section": c["section"],
                        "confidence": 0.85
                    }

        self._write_json(f"{p}_concept_subtrees.json", subtrees)
        self._write_json(f"{p}_index_directed_graph.json", {"metadata": {"total_nodes": len(directed_graph)}, "graph": dict(directed_graph)})
        self._write_json(f"{p}_polysemy_disambiguation.json", polysemy_hubs)
        self._write_json(f"{p}_drug_disease_safety_matrix.json", safety_matrix)
        self._write_json(f"{p}_early_exit_section_index.json", early_exit)

        self.log("PHASE 3", f"Built {len(subtrees)} subtrees, {len(polysemy_hubs)} polysemy hubs, and {len(early_exit)} early-exit anchors.")

    def phase_4_build_nextgen_optimizers(self):
        """Phase 4: Semantic cache, differential comparators, GBNF grammar, and BM25 weights."""
        p = self.config.asset_prefix
        self.log("PHASE 4", "Building canonical semantic cache, differentials, and GBNF grammar...")

        # Canonical Cache
        subtrees = self._read_json(f"{p}_concept_subtrees.json", default={})
        cache: Dict[str, Any] = {}
        for k, sdata in list(subtrees.items())[:300]:
            cache[k] = {
                "canonical_concept": sdata.get("parent_concept", k),
                "subfacets_summary": sdata.get("subfacets", [])[:5],
                "status": "cached"
            }
        self._write_json(f"{p}_canonical_semantic_cache.json", cache)

        # Differential Comparators
        differentials: List[Dict[str, Any]] = []
        for item in self.index_terms:
            term = item["term"]
            for sub in item["sub_entries"]:
                if re.search(r"\bvs\.?\b|distinguished from", sub, re.IGNORECASE):
                    differentials.append({
                        "parent_concept": term,
                        "differential_entry": sub,
                        "relationship": "vs_comparator"
                    })
        self._write_json(f"{p}_differential_comparators.json", differentials)

        # Page Co-occurrence Graph
        cooccur_edges: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
        # Link adjacent index terms
        for i in range(len(self.index_terms) - 1):
            t1 = self.index_terms[i]["term"]
            t2 = self.index_terms[i + 1]["term"]
            cooccur_edges[t1].append({"associated_concept": t2, "weight": 1.0})
        self._write_json(f"{p}_clinical_cooccurrence_graph.json", {
            "metadata": {"total_cooccurrence_edges": len(cooccur_edges)},
            "comorbidities": dict(cooccur_edges)
        })

        # GBNF Grammar & JSON Schema
        synonyms = self._read_json("cardiology_synonyms_and_acronyms.json", default={})
        acro_keys = list(synonyms.keys())[:50] or ["ACRONYM"]
        gbnf_rules = [
            f"# Formal GBNF Grammar for {self.config.book_title}",
            'root ::= MedicalResponse',
            'MedicalResponse ::= "{" ws "\\"acronym\\":" ws Acronym "}"',
            'ws ::= [ \\t\\n]*',
            'Acronym ::= ' + ' | '.join(f'"{a}"' for a in acro_keys)
        ]
        self._write_text(f"{p}_entity_grammar.gbnf", "\n".join(gbnf_rules) + "\n")

        json_schema = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": f"{p.capitalize()}EntityExtraction",
            "type": "object",
            "properties": {
                "identified_acronyms": {"type": "array", "items": {"type": "string", "enum": acro_keys}}
            }
        }
        self._write_json(f"{p}_entity_schema.json", json_schema)

        # BM25 Weights
        bm25_weights: Dict[str, float] = {}
        for item in self.index_terms:
            for w in re.findall(r"\b[a-z]{3,15}\b", item["term"].lower()):
                bm25_weights[w] = 3.0
        self._write_json(f"{p}_index_salience_bm25_weights.json", bm25_weights)

        self.log("PHASE 4", f"Synthesized semantic cache ({len(cache)}), differentials ({len(differentials)}), and BM25 weights.")

    def phase_5_benchmark_retrieval(self):
        """Phase 5: a REAL (if modest) retrieval benchmark computed from the built index.

        Queries are each sampled chunk's own topic string, so this is a SYNTHETIC SELF-TOPIC benchmark: an
        upper bound on lexical retrieval over this catalog, not a measure of clinical retrieval quality.
        Ties are scored pessimistically (every tied chunk ranks ahead of the gold chunk). The old version
        wrote a literal table of invented numbers (78.4% / 6.54 ms / PASS) and ran no retrieval at all."""
        p = self.config.asset_prefix
        n = len(self.chunks_catalog)
        if n < 3:
            self.benchmark_verdict = "NOT_EVALUATED"
            self.log("PHASE 5", "Fewer than 3 chunks: benchmark not evaluated")
            self._write_text("BENCHMARK_SCORECARD.md", f"# Benchmark Scorecard: {self.config.book_title}\n\nNOT EVALUATED (only {n} chunk(s)).\n")
            return

        import math
        inv = self.inverted_index
        idf = {tok: math.log(1 + n / len(docs)) for tok, docs in inv.items() if docs}

        def score_all(qtoks):
            sc: Dict[int, float] = {}
            for tok in set(qtoks):
                w = idf.get(tok)
                if w is None:
                    continue
                for d in inv[tok]:
                    sc[d] = sc.get(d, 0.0) + w
            return sc

        wanted = max(1, min(self.config.eval_triplets_count, n))
        step = max(1, n // wanted)
        sample = list(range(0, n, step))[:wanted]
        triplets, per_query = [], []
        hit1 = hit3 = disc = 0
        rr_sum = 0.0
        lat = []
        for gi in sample:
            gold = self.chunks_catalog[gi]
            qtoks = tokenize(gold["topic"])
            t0 = time.perf_counter_ns()
            sc = score_all(qtoks)
            lat.append(time.perf_counter_ns() - t0)
            g_score = sc.get(gi, 0.0)
            # Chunks of the SAME topic are equally correct answers to a topic query, so they never count as
            # competitors (a long section split into N chunks must not score as N-1 misses).
            same_topic = {d for d, c in enumerate(self.chunks_catalog) if c["topic"] == gold["topic"]}
            ahead = sum(1 for d, s in sc.items() if d not in same_topic and s >= g_score)      # pessimistic ties
            rank = 1 + ahead if g_score > 0 else n
            neg_idx, neg_score = None, -1.0
            for d, s in sc.items():
                if d not in same_topic and (s > neg_score or (s == neg_score and d < (neg_idx if neg_idx is not None else n))):
                    neg_idx, neg_score = d, s
            hit1 += rank == 1
            hit3 += rank <= 3
            rr_sum += 1.0 / rank
            disc += g_score > max(neg_score, 0.0)
            neg_id = self.chunks_catalog[neg_idx]["chunk_id"] if neg_idx is not None else None
            triplets.append({"query": gold["topic"], "gold_chunk_id": gold["chunk_id"], "hard_negative_chunk_id": neg_id})
            per_query.append({"query": gold["topic"], "gold_chunk_id": gold["chunk_id"], "rank": rank,
                              "gold_score": round(g_score, 4), "negative_score": round(max(neg_score, 0.0), 4), "latency_ns": lat[-1]})
        q = len(sample)
        lat_sorted = sorted(lat)
        p50 = lat_sorted[len(lat_sorted) // 2] / 1e6
        p95 = lat_sorted[min(len(lat_sorted) - 1, int(len(lat_sorted) * 0.95))] / 1e6
        metrics = {"hit_at_1": hit1 / q, "hit_at_3": hit3 / q, "mrr": rr_sum / q, "hard_negative_discrimination": disc / q,
                   "latency_p50_ms": p50, "latency_p95_ms": p95}
        targets = [("Hit@1", "hit_at_1", 0.75, ">="), ("Hit@3", "hit_at_3", 0.85, ">="), ("MRR", "mrr", 0.80, ">="),
                   ("Hard-negative discrimination", "hard_negative_discrimination", 0.85, ">="),
                   ("Median in-process lookup latency (ms)", "latency_p50_ms", 15.0, "<")]
        rows, all_ok = [], True
        for label, key, tgt, op in targets:
            v = metrics[key]
            ok = (v >= tgt) if op == ">=" else (v < tgt)
            all_ok &= ok
            rows.append(f"| **{label}** | {op} {tgt} | **{v:.3f}** | **{'PASS' if ok else 'FAIL'}** |")
        self.benchmark_verdict = "PASS" if all_ok else "FAIL"

        self._write_json(f"{p}_rag_eval_triplets.json", triplets)
        self._write_json(f"{p}_benchmark_raw_results.json", {"queries": per_query, "metrics": metrics, "n_chunks": n})
        card = [
            f"# Benchmark Scorecard: {self.config.book_title} ({self.config.edition})",
            "",
            "**SYNTHETIC SELF-TOPIC RETRIEVAL BENCHMARK** - each query is a chunk's own topic string, scored by lexical IDF over the",
            "compiled index. This is an upper bound for lexical retrieval over THIS catalog; it is NOT a measure of clinical",
            "retrieval quality and not an end-to-end CLI latency (that includes process start-up). Ties are scored pessimistically.",
            "",
            f"Evaluated {q} queries over {n} chunks on {time.strftime('%Y-%m-%d')}. Raw per-query results: `{p}_benchmark_raw_results.json`.",
            "",
            "| Metric | Target | Measured | Verdict |",
            "|---|:---:|:---:|:---:|",
            *rows,
            f"| In-process lookup latency P95 (ms) | - | {p95:.3f} | info |",
            "| Token prompt savings | - | not measured | n/a |",
            "",
            f"**OVERALL: {self.benchmark_verdict}**",
            "",
        ]
        self._write_text("BENCHMARK_SCORECARD.md", "\n".join(card))
        self.log("PHASE 5", f"Benchmark {self.benchmark_verdict}: Hit@1={metrics['hit_at_1']:.3f} Hit@3={metrics['hit_at_3']:.3f} "
                            f"MRR={metrics['mrr']:.3f} P50={p50:.3f}ms over {q} queries")

    def phase_6_scaffold_router_and_skill(self):
        """Phase 6: write a small REAL lexical router (see ROUTER_TEMPLATE) next to the compiled catalog."""
        self.log("PHASE 6", "Writing lexical cdss_qa_router.py (query/vignette only; other modes report 'not implemented')...")
        self._write_text("cdss_qa_router.py", ROUTER_TEMPLATE.replace("__TITLE__", self.config.book_title))
        self.log("PHASE 6", "Router written")

    def _write_json(self, filename: str, data: Any, indent: int = 2):
        self._write_text(filename, json.dumps(data, ensure_ascii=False, indent=indent))

    def _write_text(self, filename: str, text: str):
        """Single choke point for every output file, so --dry-run really writes nothing."""
        path = os.path.join(self.config.output_dir, filename)
        if self.config.dry_run:
            self.log("DRY-RUN", f"would write {path} ({len(text)} chars)")
            return
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)

    def _read_json(self, filename: str, default: Any = None) -> Any:
        path = os.path.join(self.config.output_dir, filename)
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                return json.load(f)
        return default


def main():
    parser = argparse.ArgumentParser(description="Autonomous Medical Index RAG Compiler")
    parser.add_argument("--book", type=str, required=True, help="Full title of the medical textbook")
    parser.add_argument("--edition", type=str, required=True, help="Edition string (e.g., '25th Edition')")
    parser.add_argument("--corpus", type=str, required=True, help="Path to textbook chapters root")
    parser.add_argument("--index", type=str, required=True, help="Path to index markdown_inlined.md")
    parser.add_argument("--output", type=str, required=True, help="Target directory for 26 production assets")
    parser.add_argument("--prefix", type=str, default="", help="Asset filename prefix (auto-derived if empty)")
    parser.add_argument("--eval-triplets", type=int, default=768, help="Number of benchmark evaluation triplets")
    parser.add_argument("--skip-eval", action="store_true", help="Skip running benchmark evaluation")
    parser.add_argument("--dry-run", action="store_true", help="Validate without writing files")
    parser.add_argument("--allow-benchmark-fail", action="store_true",
                        help="Exit 0 even if the computed benchmark misses its targets")
    parser.add_argument("--allow-unverified", action="store_true",
                        help="Also index chapters without a trust marker / trusted Stage 8 (logged loudly)")

    args = parser.parse_args()
    config = CompilerConfig(
        book_title=args.book,
        edition=args.edition,
        corpus_root=args.corpus,
        index_markdown_path=args.index,
        output_dir=args.output,
        asset_prefix=args.prefix,
        eval_triplets_count=args.eval_triplets,
        skip_eval=args.skip_eval,
        dry_run=args.dry_run,
        allow_unverified=args.allow_unverified
    )
    compiler = MedicalBookIndexCompiler(config)
    manifest = compiler.run_all()
    if manifest.get("benchmark_verdict") == "FAIL" and not args.allow_benchmark_fail:
        print("[COMPILER] Benchmark targets not met (see BENCHMARK_SCORECARD.md); exiting 1. "
              "Use --allow-benchmark-fail to override.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
